version: '3.9'

services:
  redis:
    container_name: redis
    env_file: .env
    image: redis:${REDIS_VERSION}
    ports:
     - ${REDIS_PORT_EXTERNAL}:6379
    command: redis-server --maxmemory ${REDIS_MAX_MEMORY} --maxmemory-policy ${REDIS_EVICTION_POLICY} --maxmemory-samples ${REDIS_MAX_SAMPLES}
    # redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - PASSWORD=${REDIS_PASSWORD}
    restart: always
    #volumes:
    #  - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "7000", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10